import SwiftUI

package struct TokenDailyBoardConversationOnlyAvatarEffectConfiguration {
    let haloColor: Color
    let accentColor: Color
    let haloOpacity: Double
    let haloScale: CGFloat
    let ringOpacity: Double
    let ringScale: CGFloat
    let scanAngle: Double
    let scanTravel: CGFloat
    let scanOpacity: Double
    let orbitOpacity: Double
    let orbitRadiusMultiplier: CGFloat
    let duration: TimeInterval
}

package enum TokenDailyBoardConversationOnlyAvatarEffectRules {
    private static func color(_ red: Double, _ green: Double, _ blue: Double) -> Color {
        Color(red: red, green: green, blue: blue)
    }

    private static let configs: [TokenDailyBoardConversationOnlyAvatarEffectConfiguration] = [
        .init(
            haloColor: color(0.98, 0.63, 0.40),
            accentColor: color(1.00, 0.86, 0.72),
            haloOpacity: 0.24,
            haloScale: 1.14,
            ringOpacity: 0.16,
            ringScale: 1.06,
            scanAngle: 14,
            scanTravel: 18,
            scanOpacity: 0.16,
            orbitOpacity: 0.12,
            orbitRadiusMultiplier: 0.58,
            duration: 0.58),
        .init(
            haloColor: color(0.62, 0.82, 1.00),
            accentColor: color(0.86, 0.95, 1.00),
            haloOpacity: 0.22,
            haloScale: 1.11,
            ringOpacity: 0.18,
            ringScale: 1.09,
            scanAngle: -18,
            scanTravel: 16,
            scanOpacity: 0.18,
            orbitOpacity: 0.10,
            orbitRadiusMultiplier: 0.54,
            duration: 0.54),
        .init(
            haloColor: color(0.84, 0.58, 1.00),
            accentColor: color(0.97, 0.82, 1.00),
            haloOpacity: 0.20,
            haloScale: 1.18,
            ringOpacity: 0.20,
            ringScale: 1.12,
            scanAngle: 24,
            scanTravel: 20,
            scanOpacity: 0.14,
            orbitOpacity: 0.15,
            orbitRadiusMultiplier: 0.60,
            duration: 0.62),
        .init(
            haloColor: color(0.52, 1.00, 0.86),
            accentColor: color(0.84, 1.00, 0.94),
            haloOpacity: 0.18,
            haloScale: 1.10,
            ringOpacity: 0.15,
            ringScale: 1.07,
            scanAngle: -28,
            scanTravel: 14,
            scanOpacity: 0.22,
            orbitOpacity: 0.18,
            orbitRadiusMultiplier: 0.52,
            duration: 0.50),
        .init(
            haloColor: color(1.00, 0.72, 0.78),
            accentColor: color(1.00, 0.90, 0.92),
            haloOpacity: 0.21,
            haloScale: 1.12,
            ringOpacity: 0.14,
            ringScale: 1.05,
            scanAngle: 0,
            scanTravel: 12,
            scanOpacity: 0.20,
            orbitOpacity: 0.08,
            orbitRadiusMultiplier: 0.50,
            duration: 0.48),
        .init(
            haloColor: color(0.98, 0.90, 0.48),
            accentColor: color(1.00, 0.98, 0.78),
            haloOpacity: 0.26,
            haloScale: 1.15,
            ringOpacity: 0.12,
            ringScale: 1.04,
            scanAngle: 12,
            scanTravel: 22,
            scanOpacity: 0.18,
            orbitOpacity: 0.10,
            orbitRadiusMultiplier: 0.56,
            duration: 0.64),
        .init(
            haloColor: color(0.56, 0.72, 1.00),
            accentColor: color(0.88, 0.92, 1.00),
            haloOpacity: 0.19,
            haloScale: 1.09,
            ringOpacity: 0.22,
            ringScale: 1.12,
            scanAngle: -32,
            scanTravel: 24,
            scanOpacity: 0.12,
            orbitOpacity: 0.20,
            orbitRadiusMultiplier: 0.64,
            duration: 0.60),
        .init(
            haloColor: color(1.00, 0.54, 0.66),
            accentColor: color(1.00, 0.82, 0.88),
            haloOpacity: 0.22,
            haloScale: 1.16,
            ringOpacity: 0.18,
            ringScale: 1.10,
            scanAngle: 36,
            scanTravel: 18,
            scanOpacity: 0.16,
            orbitOpacity: 0.14,
            orbitRadiusMultiplier: 0.62,
            duration: 0.66),
        .init(
            haloColor: color(0.56, 1.00, 0.66),
            accentColor: color(0.90, 1.00, 0.92),
            haloOpacity: 0.18,
            haloScale: 1.08,
            ringOpacity: 0.16,
            ringScale: 1.05,
            scanAngle: -8,
            scanTravel: 10,
            scanOpacity: 0.24,
            orbitOpacity: 0.10,
            orbitRadiusMultiplier: 0.48,
            duration: 0.44),
        .init(
            haloColor: color(0.98, 0.78, 0.60),
            accentColor: color(1.00, 0.96, 0.86),
            haloOpacity: 0.28,
            haloScale: 1.20,
            ringOpacity: 0.20,
            ringScale: 1.13,
            scanAngle: 18,
            scanTravel: 26,
            scanOpacity: 0.18,
            orbitOpacity: 0.18,
            orbitRadiusMultiplier: 0.66,
            duration: 0.70),
        .init(
            haloColor: color(0.74, 0.62, 1.00),
            accentColor: color(0.96, 0.92, 1.00),
            haloOpacity: 0.20,
            haloScale: 1.12,
            ringOpacity: 0.14,
            ringScale: 1.06,
            scanAngle: -22,
            scanTravel: 18,
            scanOpacity: 0.20,
            orbitOpacity: 0.12,
            orbitRadiusMultiplier: 0.58,
            duration: 0.56),
        .init(
            haloColor: color(0.64, 0.90, 0.94),
            accentColor: color(0.92, 0.99, 1.00),
            haloOpacity: 0.17,
            haloScale: 1.06,
            ringOpacity: 0.24,
            ringScale: 1.14,
            scanAngle: 28,
            scanTravel: 28,
            scanOpacity: 0.10,
            orbitOpacity: 0.16,
            orbitRadiusMultiplier: 0.70,
            duration: 0.72),
        .init(
            haloColor: color(1.00, 0.62, 0.54),
            accentColor: color(1.00, 0.90, 0.82),
            haloOpacity: 0.23,
            haloScale: 1.13,
            ringOpacity: 0.15,
            ringScale: 1.05,
            scanAngle: 8,
            scanTravel: 14,
            scanOpacity: 0.24,
            orbitOpacity: 0.08,
            orbitRadiusMultiplier: 0.52,
            duration: 0.46),
        .init(
            haloColor: color(0.66, 0.78, 1.00),
            accentColor: color(0.94, 0.97, 1.00),
            haloOpacity: 0.18,
            haloScale: 1.10,
            ringOpacity: 0.16,
            ringScale: 1.08,
            scanAngle: -14,
            scanTravel: 20,
            scanOpacity: 0.18,
            orbitOpacity: 0.22,
            orbitRadiusMultiplier: 0.72,
            duration: 0.68),
        .init(
            haloColor: color(0.92, 0.62, 0.96),
            accentColor: color(1.00, 0.88, 1.00),
            haloOpacity: 0.21,
            haloScale: 1.17,
            ringOpacity: 0.17,
            ringScale: 1.09,
            scanAngle: 30,
            scanTravel: 16,
            scanOpacity: 0.20,
            orbitOpacity: 0.12,
            orbitRadiusMultiplier: 0.50,
            duration: 0.52),
        .init(
            haloColor: color(0.58, 0.98, 0.82),
            accentColor: color(0.86, 1.00, 0.94),
            haloOpacity: 0.19,
            haloScale: 1.09,
            ringOpacity: 0.18,
            ringScale: 1.11,
            scanAngle: -26,
            scanTravel: 24,
            scanOpacity: 0.16,
            orbitOpacity: 0.14,
            orbitRadiusMultiplier: 0.60,
            duration: 0.60),
        .init(
            haloColor: color(1.00, 0.82, 0.46),
            accentColor: color(1.00, 0.97, 0.80),
            haloOpacity: 0.27,
            haloScale: 1.18,
            ringOpacity: 0.12,
            ringScale: 1.04,
            scanAngle: 6,
            scanTravel: 12,
            scanOpacity: 0.26,
            orbitOpacity: 0.06,
            orbitRadiusMultiplier: 0.44,
            duration: 0.42),
        .init(
            haloColor: color(0.60, 0.68, 1.00),
            accentColor: color(0.88, 0.92, 1.00),
            haloOpacity: 0.18,
            haloScale: 1.07,
            ringOpacity: 0.24,
            ringScale: 1.15,
            scanAngle: -40,
            scanTravel: 30,
            scanOpacity: 0.12,
            orbitOpacity: 0.20,
            orbitRadiusMultiplier: 0.74,
            duration: 0.74),
        .init(
            haloColor: color(1.00, 0.56, 0.78),
            accentColor: color(1.00, 0.86, 0.94),
            haloOpacity: 0.20,
            haloScale: 1.12,
            ringOpacity: 0.16,
            ringScale: 1.07,
            scanAngle: 34,
            scanTravel: 22,
            scanOpacity: 0.14,
            orbitOpacity: 0.18,
            orbitRadiusMultiplier: 0.68,
            duration: 0.62),
        .init(
            haloColor: color(0.54, 0.92, 1.00),
            accentColor: color(0.86, 0.98, 1.00),
            haloOpacity: 0.16,
            haloScale: 1.05,
            ringOpacity: 0.20,
            ringScale: 1.10,
            scanAngle: -12,
            scanTravel: 16,
            scanOpacity: 0.20,
            orbitOpacity: 0.10,
            orbitRadiusMultiplier: 0.56,
            duration: 0.48),
        .init(
            haloColor: color(0.96, 0.66, 0.58),
            accentColor: color(1.00, 0.92, 0.86),
            haloOpacity: 0.25,
            haloScale: 1.16,
            ringOpacity: 0.20,
            ringScale: 1.12,
            scanAngle: 20,
            scanTravel: 26,
            scanOpacity: 0.14,
            orbitOpacity: 0.16,
            orbitRadiusMultiplier: 0.64,
            duration: 0.66),
        .init(
            haloColor: color(0.74, 0.66, 1.00),
            accentColor: color(0.96, 0.94, 1.00),
            haloOpacity: 0.18,
            haloScale: 1.09,
            ringOpacity: 0.14,
            ringScale: 1.05,
            scanAngle: -24,
            scanTravel: 18,
            scanOpacity: 0.22,
            orbitOpacity: 0.12,
            orbitRadiusMultiplier: 0.58,
            duration: 0.54),
        .init(
            haloColor: color(0.74, 0.98, 0.62),
            accentColor: color(0.94, 1.00, 0.86),
            haloOpacity: 0.19,
            haloScale: 1.11,
            ringOpacity: 0.22,
            ringScale: 1.13,
            scanAngle: 10,
            scanTravel: 20,
            scanOpacity: 0.16,
            orbitOpacity: 0.14,
            orbitRadiusMultiplier: 0.62,
            duration: 0.58),
        .init(
            haloColor: color(1.00, 0.74, 0.52),
            accentColor: color(1.00, 0.96, 0.82),
            haloOpacity: 0.24,
            haloScale: 1.15,
            ringOpacity: 0.16,
            ringScale: 1.08,
            scanAngle: 26,
            scanTravel: 24,
            scanOpacity: 0.18,
            orbitOpacity: 0.10,
            orbitRadiusMultiplier: 0.54,
            duration: 0.60),
        .init(
            haloColor: color(0.66, 0.86, 1.00),
            accentColor: color(0.92, 0.98, 1.00),
            haloOpacity: 0.16,
            haloScale: 1.08,
            ringOpacity: 0.18,
            ringScale: 1.09,
            scanAngle: -30,
            scanTravel: 22,
            scanOpacity: 0.18,
            orbitOpacity: 0.20,
            orbitRadiusMultiplier: 0.70,
            duration: 0.68),
        .init(
            haloColor: color(0.98, 0.60, 0.88),
            accentColor: color(1.00, 0.88, 0.98),
            haloOpacity: 0.22,
            haloScale: 1.14,
            ringOpacity: 0.18,
            ringScale: 1.11,
            scanAngle: 40,
            scanTravel: 30,
            scanOpacity: 0.10,
            orbitOpacity: 0.22,
            orbitRadiusMultiplier: 0.74,
            duration: 0.76),
        .init(
            haloColor: color(0.58, 1.00, 0.92),
            accentColor: color(0.88, 1.00, 0.96),
            haloOpacity: 0.18,
            haloScale: 1.07,
            ringOpacity: 0.16,
            ringScale: 1.07,
            scanAngle: -4,
            scanTravel: 12,
            scanOpacity: 0.24,
            orbitOpacity: 0.08,
            orbitRadiusMultiplier: 0.48,
            duration: 0.44),
        .init(
            haloColor: color(0.94, 0.84, 0.54),
            accentColor: color(1.00, 0.98, 0.84),
            haloOpacity: 0.26,
            haloScale: 1.19,
            ringOpacity: 0.14,
            ringScale: 1.06,
            scanAngle: 16,
            scanTravel: 28,
            scanOpacity: 0.16,
            orbitOpacity: 0.14,
            orbitRadiusMultiplier: 0.66,
            duration: 0.70),
        .init(
            haloColor: color(0.60, 0.74, 1.00),
            accentColor: color(0.90, 0.95, 1.00),
            haloOpacity: 0.17,
            haloScale: 1.08,
            ringOpacity: 0.24,
            ringScale: 1.14,
            scanAngle: -36,
            scanTravel: 26,
            scanOpacity: 0.14,
            orbitOpacity: 0.18,
            orbitRadiusMultiplier: 0.72,
            duration: 0.72),
        .init(
            haloColor: color(1.00, 0.68, 0.70),
            accentColor: color(1.00, 0.92, 0.92),
            haloOpacity: 0.22,
            haloScale: 1.13,
            ringOpacity: 0.18,
            ringScale: 1.09,
            scanAngle: 22,
            scanTravel: 20,
            scanOpacity: 0.20,
            orbitOpacity: 0.12,
            orbitRadiusMultiplier: 0.60,
            duration: 0.58),
    ]

    package static func configuration(
        for preset: TokenDailyBoardConversationOnlyAvatarEffectPreset)
        -> TokenDailyBoardConversationOnlyAvatarEffectConfiguration
    {
        self.configs[preset.ordinal]
    }
}

package struct TokenDailyBoardConversationOnlyBackgroundEffectConfiguration {
    let fillColors: [Color]
    let fillStartPoint: UnitPoint
    let fillEndPoint: UnitPoint
    let sweepColors: [Color]
    let sweepStartPoint: UnitPoint
    let sweepEndPoint: UnitPoint
    let sweepWidthMultiplier: CGFloat
    let sweepBlurMultiplier: CGFloat
    let fillOpacityMultiplier: Double
    let sweepOpacityMultiplier: Double
}

package enum TokenDailyBoardConversationOnlyBackgroundEffectRules {
    private static func color(_ red: Double, _ green: Double, _ blue: Double) -> Color {
        Color(red: red, green: green, blue: blue)
    }

    private static let configs: [TokenDailyBoardConversationOnlyBackgroundEffectConfiguration] = [
        .init(
            fillColors: [color(0.26, 0.10, 0.12), color(0.54, 0.22, 0.20), color(0.96, 0.92, 0.88)],
            fillStartPoint: .topLeading,
            fillEndPoint: .bottomTrailing,
            sweepColors: [Color.clear, color(0.82, 0.42, 0.32), color(0.98, 0.95, 0.90), Color.clear],
            sweepStartPoint: .leading,
            sweepEndPoint: .trailing,
            sweepWidthMultiplier: 0.74,
            sweepBlurMultiplier: 1.00,
            fillOpacityMultiplier: 1.00,
            sweepOpacityMultiplier: 1.00),
        .init(
            fillColors: [color(0.20, 0.11, 0.24), color(0.44, 0.18, 0.38), color(0.93, 0.88, 0.96)],
            fillStartPoint: .top,
            fillEndPoint: .bottom,
            sweepColors: [Color.clear, color(0.66, 0.38, 0.78), color(0.96, 0.90, 1.00), Color.clear],
            sweepStartPoint: .bottomLeading,
            sweepEndPoint: .topTrailing,
            sweepWidthMultiplier: 0.68,
            sweepBlurMultiplier: 0.92,
            fillOpacityMultiplier: 0.94,
            sweepOpacityMultiplier: 1.08),
        .init(
            fillColors: [color(0.14, 0.16, 0.24), color(0.22, 0.32, 0.52), color(0.88, 0.93, 1.00)],
            fillStartPoint: .leading,
            fillEndPoint: .trailing,
            sweepColors: [Color.clear, color(0.42, 0.62, 0.98), color(0.94, 0.98, 1.00), Color.clear],
            sweepStartPoint: .topLeading,
            sweepEndPoint: .bottomTrailing,
            sweepWidthMultiplier: 0.80,
            sweepBlurMultiplier: 0.96,
            fillOpacityMultiplier: 0.92,
            sweepOpacityMultiplier: 1.02),
        .init(
            fillColors: [color(0.12, 0.18, 0.16), color(0.18, 0.40, 0.30), color(0.86, 0.98, 0.92)],
            fillStartPoint: .topTrailing,
            fillEndPoint: .bottomLeading,
            sweepColors: [Color.clear, color(0.40, 0.78, 0.58), color(0.92, 1.00, 0.96), Color.clear],
            sweepStartPoint: .leading,
            sweepEndPoint: .trailing,
            sweepWidthMultiplier: 0.72,
            sweepBlurMultiplier: 0.88,
            fillOpacityMultiplier: 0.90,
            sweepOpacityMultiplier: 0.98),
        .init(
            fillColors: [color(0.28, 0.12, 0.20), color(0.50, 0.18, 0.30), color(0.98, 0.88, 0.92)],
            fillStartPoint: .bottomLeading,
            fillEndPoint: .topTrailing,
            sweepColors: [Color.clear, color(0.88, 0.42, 0.62), color(1.00, 0.94, 0.96), Color.clear],
            sweepStartPoint: .top,
            sweepEndPoint: .bottom,
            sweepWidthMultiplier: 0.76,
            sweepBlurMultiplier: 0.94,
            fillOpacityMultiplier: 0.96,
            sweepOpacityMultiplier: 1.00),
        .init(
            fillColors: [color(0.26, 0.18, 0.10), color(0.54, 0.34, 0.12), color(1.00, 0.96, 0.84)],
            fillStartPoint: .topLeading,
            fillEndPoint: .bottomTrailing,
            sweepColors: [Color.clear, color(0.92, 0.72, 0.26), color(1.00, 0.98, 0.90), Color.clear],
            sweepStartPoint: .leading,
            sweepEndPoint: .trailing,
            sweepWidthMultiplier: 0.70,
            sweepBlurMultiplier: 0.86,
            fillOpacityMultiplier: 0.88,
            sweepOpacityMultiplier: 1.06),
        .init(
            fillColors: [color(0.18, 0.12, 0.26), color(0.30, 0.24, 0.56), color(0.90, 0.88, 1.00)],
            fillStartPoint: .bottom,
            fillEndPoint: .top,
            sweepColors: [Color.clear, color(0.52, 0.46, 1.00), color(0.94, 0.94, 1.00), Color.clear],
            sweepStartPoint: .bottomTrailing,
            sweepEndPoint: .topLeading,
            sweepWidthMultiplier: 0.82,
            sweepBlurMultiplier: 1.04,
            fillOpacityMultiplier: 0.98,
            sweepOpacityMultiplier: 0.94),
        .init(
            fillColors: [color(0.16, 0.18, 0.14), color(0.28, 0.40, 0.24), color(0.92, 0.98, 0.86)],
            fillStartPoint: .leading,
            fillEndPoint: .bottomTrailing,
            sweepColors: [Color.clear, color(0.60, 0.86, 0.38), color(0.96, 1.00, 0.92), Color.clear],
            sweepStartPoint: .topTrailing,
            sweepEndPoint: .bottomLeading,
            sweepWidthMultiplier: 0.66,
            sweepBlurMultiplier: 0.84,
            fillOpacityMultiplier: 0.84,
            sweepOpacityMultiplier: 1.12),
        .init(
            fillColors: [color(0.22, 0.12, 0.16), color(0.42, 0.16, 0.24), color(0.98, 0.90, 0.90)],
            fillStartPoint: .top,
            fillEndPoint: .bottom,
            sweepColors: [Color.clear, color(0.92, 0.38, 0.44), color(1.00, 0.96, 0.94), Color.clear],
            sweepStartPoint: .leading,
            sweepEndPoint: .trailing,
            sweepWidthMultiplier: 0.78,
            sweepBlurMultiplier: 0.90,
            fillOpacityMultiplier: 0.86,
            sweepOpacityMultiplier: 1.10),
        .init(
            fillColors: [color(0.12, 0.16, 0.22), color(0.18, 0.28, 0.48), color(0.90, 0.96, 1.00)],
            fillStartPoint: .topLeading,
            fillEndPoint: .bottom,
            sweepColors: [Color.clear, color(0.38, 0.72, 1.00), color(0.92, 0.98, 1.00), Color.clear],
            sweepStartPoint: .bottomLeading,
            sweepEndPoint: .topTrailing,
            sweepWidthMultiplier: 0.74,
            sweepBlurMultiplier: 1.08,
            fillOpacityMultiplier: 0.94,
            sweepOpacityMultiplier: 0.96),
        .init(
            fillColors: [color(0.18, 0.12, 0.22), color(0.36, 0.18, 0.46), color(0.96, 0.88, 1.00)],
            fillStartPoint: .topTrailing,
            fillEndPoint: .bottomLeading,
            sweepColors: [Color.clear, color(0.78, 0.40, 0.98), color(0.98, 0.92, 1.00), Color.clear],
            sweepStartPoint: .topLeading,
            sweepEndPoint: .bottomTrailing,
            sweepWidthMultiplier: 0.72,
            sweepBlurMultiplier: 0.98,
            fillOpacityMultiplier: 0.92,
            sweepOpacityMultiplier: 1.04),
        .init(
            fillColors: [color(0.10, 0.18, 0.22), color(0.12, 0.36, 0.40), color(0.86, 0.98, 1.00)],
            fillStartPoint: .top,
            fillEndPoint: .bottom,
            sweepColors: [Color.clear, color(0.30, 0.86, 0.96), color(0.90, 1.00, 1.00), Color.clear],
            sweepStartPoint: .leading,
            sweepEndPoint: .trailing,
            sweepWidthMultiplier: 0.68,
            sweepBlurMultiplier: 0.88,
            fillOpacityMultiplier: 0.88,
            sweepOpacityMultiplier: 1.08),
        .init(
            fillColors: [color(0.22, 0.16, 0.10), color(0.42, 0.30, 0.16), color(0.98, 0.96, 0.86)],
            fillStartPoint: .bottomLeading,
            fillEndPoint: .topTrailing,
            sweepColors: [Color.clear, color(0.96, 0.82, 0.36), color(1.00, 0.99, 0.92), Color.clear],
            sweepStartPoint: .topTrailing,
            sweepEndPoint: .bottomLeading,
            sweepWidthMultiplier: 0.84,
            sweepBlurMultiplier: 1.06,
            fillOpacityMultiplier: 1.00,
            sweepOpacityMultiplier: 0.92),
        .init(
            fillColors: [color(0.14, 0.18, 0.18), color(0.18, 0.34, 0.30), color(0.88, 0.98, 0.94)],
            fillStartPoint: .leading,
            fillEndPoint: .trailing,
            sweepColors: [Color.clear, color(0.34, 0.92, 0.72), color(0.94, 1.00, 0.98), Color.clear],
            sweepStartPoint: .bottom,
            sweepEndPoint: .top,
            sweepWidthMultiplier: 0.64,
            sweepBlurMultiplier: 0.82,
            fillOpacityMultiplier: 0.82,
            sweepOpacityMultiplier: 1.14),
        .init(
            fillColors: [color(0.24, 0.10, 0.26), color(0.46, 0.16, 0.42), color(0.98, 0.86, 0.98)],
            fillStartPoint: .topLeading,
            fillEndPoint: .bottomTrailing,
            sweepColors: [Color.clear, color(0.98, 0.44, 0.86), color(1.00, 0.92, 0.98), Color.clear],
            sweepStartPoint: .leading,
            sweepEndPoint: .trailing,
            sweepWidthMultiplier: 0.80,
            sweepBlurMultiplier: 1.02,
            fillOpacityMultiplier: 0.94,
            sweepOpacityMultiplier: 1.00),
        .init(
            fillColors: [color(0.12, 0.20, 0.12), color(0.18, 0.42, 0.18), color(0.88, 1.00, 0.88)],
            fillStartPoint: .top,
            fillEndPoint: .bottom,
            sweepColors: [Color.clear, color(0.46, 0.98, 0.48), color(0.94, 1.00, 0.94), Color.clear],
            sweepStartPoint: .topLeading,
            sweepEndPoint: .bottomTrailing,
            sweepWidthMultiplier: 0.70,
            sweepBlurMultiplier: 0.90,
            fillOpacityMultiplier: 0.86,
            sweepOpacityMultiplier: 1.04),
        .init(
            fillColors: [color(0.26, 0.12, 0.12), color(0.48, 0.18, 0.18), color(1.00, 0.90, 0.86)],
            fillStartPoint: .bottom,
            fillEndPoint: .top,
            sweepColors: [Color.clear, color(1.00, 0.54, 0.38), color(1.00, 0.95, 0.90), Color.clear],
            sweepStartPoint: .bottomLeading,
            sweepEndPoint: .topTrailing,
            sweepWidthMultiplier: 0.78,
            sweepBlurMultiplier: 0.92,
            fillOpacityMultiplier: 0.90,
            sweepOpacityMultiplier: 1.06),
        .init(
            fillColors: [color(0.12, 0.14, 0.28), color(0.18, 0.24, 0.58), color(0.86, 0.90, 1.00)],
            fillStartPoint: .topTrailing,
            fillEndPoint: .bottomLeading,
            sweepColors: [Color.clear, color(0.34, 0.52, 1.00), color(0.92, 0.94, 1.00), Color.clear],
            sweepStartPoint: .top,
            sweepEndPoint: .bottom,
            sweepWidthMultiplier: 0.86,
            sweepBlurMultiplier: 1.10,
            fillOpacityMultiplier: 1.00,
            sweepOpacityMultiplier: 0.90),
        .init(
            fillColors: [color(0.14, 0.20, 0.26), color(0.18, 0.36, 0.54), color(0.84, 0.96, 1.00)],
            fillStartPoint: .leading,
            fillEndPoint: .bottomTrailing,
            sweepColors: [Color.clear, color(0.26, 0.84, 1.00), color(0.90, 0.99, 1.00), Color.clear],
            sweepStartPoint: .bottomTrailing,
            sweepEndPoint: .topLeading,
            sweepWidthMultiplier: 0.68,
            sweepBlurMultiplier: 0.94,
            fillOpacityMultiplier: 0.86,
            sweepOpacityMultiplier: 1.08),
        .init(
            fillColors: [color(0.20, 0.12, 0.24), color(0.34, 0.16, 0.52), color(0.94, 0.88, 1.00)],
            fillStartPoint: .topLeading,
            fillEndPoint: .bottomTrailing,
            sweepColors: [Color.clear, color(0.64, 0.36, 1.00), color(0.96, 0.92, 1.00), Color.clear],
            sweepStartPoint: .leading,
            sweepEndPoint: .trailing,
            sweepWidthMultiplier: 0.74,
            sweepBlurMultiplier: 1.00,
            fillOpacityMultiplier: 0.92,
            sweepOpacityMultiplier: 1.02),
        .init(
            fillColors: [color(0.10, 0.18, 0.22), color(0.18, 0.30, 0.36), color(0.88, 0.98, 0.98)],
            fillStartPoint: .bottomLeading,
            fillEndPoint: .topTrailing,
            sweepColors: [Color.clear, color(0.30, 0.88, 0.90), color(0.94, 1.00, 1.00), Color.clear],
            sweepStartPoint: .topTrailing,
            sweepEndPoint: .bottomLeading,
            sweepWidthMultiplier: 0.72,
            sweepBlurMultiplier: 0.88,
            fillOpacityMultiplier: 0.84,
            sweepOpacityMultiplier: 1.12),
        .init(
            fillColors: [color(0.24, 0.14, 0.12), color(0.50, 0.22, 0.14), color(1.00, 0.92, 0.84)],
            fillStartPoint: .top,
            fillEndPoint: .bottom,
            sweepColors: [Color.clear, color(1.00, 0.64, 0.26), color(1.00, 0.98, 0.90), Color.clear],
            sweepStartPoint: .leading,
            sweepEndPoint: .trailing,
            sweepWidthMultiplier: 0.80,
            sweepBlurMultiplier: 0.98,
            fillOpacityMultiplier: 0.94,
            sweepOpacityMultiplier: 1.00),
        .init(
            fillColors: [color(0.18, 0.18, 0.12), color(0.34, 0.34, 0.16), color(0.96, 0.98, 0.84)],
            fillStartPoint: .leading,
            fillEndPoint: .trailing,
            sweepColors: [Color.clear, color(0.82, 0.92, 0.32), color(0.98, 1.00, 0.90), Color.clear],
            sweepStartPoint: .bottom,
            sweepEndPoint: .top,
            sweepWidthMultiplier: 0.66,
            sweepBlurMultiplier: 0.82,
            fillOpacityMultiplier: 0.82,
            sweepOpacityMultiplier: 1.16),
        .init(
            fillColors: [color(0.16, 0.14, 0.26), color(0.26, 0.20, 0.58), color(0.90, 0.90, 1.00)],
            fillStartPoint: .bottom,
            fillEndPoint: .top,
            sweepColors: [Color.clear, color(0.46, 0.42, 1.00), color(0.92, 0.94, 1.00), Color.clear],
            sweepStartPoint: .bottomLeading,
            sweepEndPoint: .topTrailing,
            sweepWidthMultiplier: 0.84,
            sweepBlurMultiplier: 1.12,
            fillOpacityMultiplier: 0.98,
            sweepOpacityMultiplier: 0.94),
        .init(
            fillColors: [color(0.16, 0.18, 0.16), color(0.24, 0.34, 0.24), color(0.92, 1.00, 0.92)],
            fillStartPoint: .topTrailing,
            fillEndPoint: .bottomLeading,
            sweepColors: [Color.clear, color(0.50, 1.00, 0.52), color(0.96, 1.00, 0.96), Color.clear],
            sweepStartPoint: .topLeading,
            sweepEndPoint: .bottomTrailing,
            sweepWidthMultiplier: 0.70,
            sweepBlurMultiplier: 0.92,
            fillOpacityMultiplier: 0.88,
            sweepOpacityMultiplier: 1.06),
        .init(
            fillColors: [color(0.26, 0.12, 0.18), color(0.52, 0.18, 0.26), color(1.00, 0.90, 0.94)],
            fillStartPoint: .leading,
            fillEndPoint: .bottomTrailing,
            sweepColors: [Color.clear, color(1.00, 0.46, 0.64), color(1.00, 0.94, 0.96), Color.clear],
            sweepStartPoint: .bottomTrailing,
            sweepEndPoint: .topLeading,
            sweepWidthMultiplier: 0.76,
            sweepBlurMultiplier: 0.96,
            fillOpacityMultiplier: 0.90,
            sweepOpacityMultiplier: 1.08),
        .init(
            fillColors: [color(0.12, 0.18, 0.28), color(0.18, 0.28, 0.62), color(0.86, 0.92, 1.00)],
            fillStartPoint: .topLeading,
            fillEndPoint: .bottomTrailing,
            sweepColors: [Color.clear, color(0.22, 0.70, 1.00), color(0.88, 0.98, 1.00), Color.clear],
            sweepStartPoint: .leading,
            sweepEndPoint: .trailing,
            sweepWidthMultiplier: 0.82,
            sweepBlurMultiplier: 1.04,
            fillOpacityMultiplier: 0.96,
            sweepOpacityMultiplier: 0.98),
        .init(
            fillColors: [color(0.18, 0.12, 0.18), color(0.30, 0.16, 0.30), color(0.96, 0.88, 0.96)],
            fillStartPoint: .bottomLeading,
            fillEndPoint: .topTrailing,
            sweepColors: [Color.clear, color(0.78, 0.34, 0.82), color(0.98, 0.92, 0.98), Color.clear],
            sweepStartPoint: .topTrailing,
            sweepEndPoint: .bottomLeading,
            sweepWidthMultiplier: 0.74,
            sweepBlurMultiplier: 0.90,
            fillOpacityMultiplier: 0.88,
            sweepOpacityMultiplier: 1.12),
        .init(
            fillColors: [color(0.14, 0.20, 0.20), color(0.18, 0.38, 0.38), color(0.86, 1.00, 1.00)],
            fillStartPoint: .top,
            fillEndPoint: .bottom,
            sweepColors: [Color.clear, color(0.26, 0.96, 0.96), color(0.92, 1.00, 1.00), Color.clear],
            sweepStartPoint: .topLeading,
            sweepEndPoint: .bottomTrailing,
            sweepWidthMultiplier: 0.68,
            sweepBlurMultiplier: 0.86,
            fillOpacityMultiplier: 0.84,
            sweepOpacityMultiplier: 1.10),
        .init(
            fillColors: [color(0.18, 0.14, 0.22), color(0.34, 0.22, 0.42), color(0.96, 0.92, 1.00)],
            fillStartPoint: .leading,
            fillEndPoint: .trailing,
            sweepColors: [Color.clear, color(0.84, 0.54, 1.00), color(0.98, 0.96, 1.00), Color.clear],
            sweepStartPoint: .bottom,
            sweepEndPoint: .top,
            sweepWidthMultiplier: 0.78,
            sweepBlurMultiplier: 1.06,
            fillOpacityMultiplier: 0.92,
            sweepOpacityMultiplier: 1.04),
    ]

    package static func configuration(
        for preset: TokenDailyBoardConversationOnlyBackgroundEffectPreset)
        -> TokenDailyBoardConversationOnlyBackgroundEffectConfiguration
    {
        self.configs[preset.ordinal]
    }
}

package struct TokenDailyBoardConversationOnlyTextEffectConfiguration {
    let initialOpacity: Double
    let initialOffset: CGSize
    let initialScale: CGFloat
    let initialBlur: CGFloat
    let initialBrightness: Double
    let settleBrightness: Double
    let shadowColor: Color
    let shadowOpacity: Double
    let shadowRadius: CGFloat
    let shadowYOffset: CGFloat
    let rotationDegrees: Double
    let duration: TimeInterval
}

package enum TokenDailyBoardConversationOnlyTextEffectRules {
    private static func color(_ red: Double, _ green: Double, _ blue: Double) -> Color {
        Color(red: red, green: green, blue: blue)
    }

    private static let configs: [TokenDailyBoardConversationOnlyTextEffectConfiguration] = [
        .init(
            initialOpacity: 0.18,
            initialOffset: CGSize(width: 0, height: 8),
            initialScale: 0.98,
            initialBlur: 8,
            initialBrightness: 0.12,
            settleBrightness: 0.00,
            shadowColor: color(1.00, 0.82, 0.60),
            shadowOpacity: 0.10,
            shadowRadius: 10,
            shadowYOffset: 2,
            rotationDegrees: 0,
            duration: 0.36),
        .init(
            initialOpacity: 0.14,
            initialOffset: CGSize(width: 10, height: 0),
            initialScale: 0.96,
            initialBlur: 10,
            initialBrightness: 0.10,
            settleBrightness: 0.00,
            shadowColor: color(0.62, 0.84, 1.00),
            shadowOpacity: 0.12,
            shadowRadius: 12,
            shadowYOffset: 0,
            rotationDegrees: -4,
            duration: 0.34),
        .init(
            initialOpacity: 0.20,
            initialOffset: CGSize(width: -10, height: 0),
            initialScale: 0.97,
            initialBlur: 12,
            initialBrightness: 0.08,
            settleBrightness: 0.00,
            shadowColor: color(0.88, 0.70, 1.00),
            shadowOpacity: 0.14,
            shadowRadius: 14,
            shadowYOffset: 0,
            rotationDegrees: 4,
            duration: 0.38),
        .init(
            initialOpacity: 0.22,
            initialOffset: CGSize(width: 0, height: -10),
            initialScale: 1.04,
            initialBlur: 7,
            initialBrightness: 0.14,
            settleBrightness: 0.00,
            shadowColor: color(0.72, 1.00, 0.86),
            shadowOpacity: 0.10,
            shadowRadius: 10,
            shadowYOffset: 3,
            rotationDegrees: 0,
            duration: 0.32),
        .init(
            initialOpacity: 0.16,
            initialOffset: CGSize(width: 8, height: -6),
            initialScale: 0.95,
            initialBlur: 9,
            initialBrightness: 0.08,
            settleBrightness: 0.02,
            shadowColor: color(1.00, 0.72, 0.78),
            shadowOpacity: 0.12,
            shadowRadius: 11,
            shadowYOffset: 2,
            rotationDegrees: -3,
            duration: 0.35),
        .init(
            initialOpacity: 0.18,
            initialOffset: CGSize(width: -8, height: 6),
            initialScale: 1.02,
            initialBlur: 11,
            initialBrightness: 0.10,
            settleBrightness: 0.01,
            shadowColor: color(1.00, 0.88, 0.52),
            shadowOpacity: 0.14,
            shadowRadius: 13,
            shadowYOffset: 1,
            rotationDegrees: 3,
            duration: 0.37),
        .init(
            initialOpacity: 0.12,
            initialOffset: CGSize(width: 12, height: 4),
            initialScale: 0.94,
            initialBlur: 14,
            initialBrightness: 0.06,
            settleBrightness: 0.00,
            shadowColor: color(0.70, 0.76, 1.00),
            shadowOpacity: 0.16,
            shadowRadius: 15,
            shadowYOffset: 0,
            rotationDegrees: -5,
            duration: 0.40),
        .init(
            initialOpacity: 0.24,
            initialOffset: CGSize(width: -12, height: -4),
            initialScale: 1.05,
            initialBlur: 8,
            initialBrightness: 0.12,
            settleBrightness: 0.02,
            shadowColor: color(1.00, 0.66, 0.72),
            shadowOpacity: 0.10,
            shadowRadius: 10,
            shadowYOffset: 2,
            rotationDegrees: 5,
            duration: 0.33),
        .init(
            initialOpacity: 0.14,
            initialOffset: CGSize(width: 0, height: 12),
            initialScale: 0.97,
            initialBlur: 10,
            initialBrightness: 0.04,
            settleBrightness: 0.00,
            shadowColor: color(0.64, 1.00, 0.72),
            shadowOpacity: 0.12,
            shadowRadius: 9,
            shadowYOffset: 4,
            rotationDegrees: 0,
            duration: 0.34),
        .init(
            initialOpacity: 0.22,
            initialOffset: CGSize(width: 14, height: 0),
            initialScale: 0.93,
            initialBlur: 13,
            initialBrightness: 0.08,
            settleBrightness: 0.03,
            shadowColor: color(1.00, 0.82, 0.64),
            shadowOpacity: 0.14,
            shadowRadius: 16,
            shadowYOffset: 0,
            rotationDegrees: -6,
            duration: 0.42),
        .init(
            initialOpacity: 0.18,
            initialOffset: CGSize(width: -14, height: 0),
            initialScale: 0.95,
            initialBlur: 12,
            initialBrightness: 0.10,
            settleBrightness: 0.01,
            shadowColor: color(0.76, 0.68, 1.00),
            shadowOpacity: 0.12,
            shadowRadius: 13,
            shadowYOffset: 0,
            rotationDegrees: 6,
            duration: 0.39),
        .init(
            initialOpacity: 0.16,
            initialOffset: CGSize(width: 6, height: -10),
            initialScale: 1.03,
            initialBlur: 9,
            initialBrightness: 0.12,
            settleBrightness: 0.00,
            shadowColor: color(0.70, 0.94, 1.00),
            shadowOpacity: 0.10,
            shadowRadius: 11,
            shadowYOffset: 3,
            rotationDegrees: -2,
            duration: 0.31),
        .init(
            initialOpacity: 0.20,
            initialOffset: CGSize(width: -6, height: 10),
            initialScale: 0.96,
            initialBlur: 10,
            initialBrightness: 0.06,
            settleBrightness: 0.02,
            shadowColor: color(1.00, 0.70, 0.58),
            shadowOpacity: 0.14,
            shadowRadius: 12,
            shadowYOffset: 2,
            rotationDegrees: 2,
            duration: 0.36),
        .init(
            initialOpacity: 0.12,
            initialOffset: CGSize(width: 10, height: 8),
            initialScale: 0.92,
            initialBlur: 15,
            initialBrightness: 0.08,
            settleBrightness: 0.00,
            shadowColor: color(0.72, 0.88, 1.00),
            shadowOpacity: 0.18,
            shadowRadius: 18,
            shadowYOffset: 1,
            rotationDegrees: -7,
            duration: 0.44),
        .init(
            initialOpacity: 0.24,
            initialOffset: CGSize(width: -10, height: -8),
            initialScale: 1.06,
            initialBlur: 7,
            initialBrightness: 0.14,
            settleBrightness: 0.01,
            shadowColor: color(0.96, 0.72, 1.00),
            shadowOpacity: 0.12,
            shadowRadius: 10,
            shadowYOffset: 2,
            rotationDegrees: 7,
            duration: 0.33),
        .init(
            initialOpacity: 0.18,
            initialOffset: CGSize(width: 0, height: -12),
            initialScale: 1.04,
            initialBlur: 8,
            initialBrightness: 0.16,
            settleBrightness: 0.00,
            shadowColor: color(0.60, 1.00, 0.88),
            shadowOpacity: 0.10,
            shadowRadius: 10,
            shadowYOffset: 4,
            rotationDegrees: 0,
            duration: 0.30),
        .init(
            initialOpacity: 0.14,
            initialOffset: CGSize(width: 12, height: -6),
            initialScale: 0.94,
            initialBlur: 11,
            initialBrightness: 0.04,
            settleBrightness: 0.02,
            shadowColor: color(1.00, 0.90, 0.58),
            shadowOpacity: 0.16,
            shadowRadius: 15,
            shadowYOffset: 1,
            rotationDegrees: -4,
            duration: 0.41),
        .init(
            initialOpacity: 0.22,
            initialOffset: CGSize(width: -12, height: 6),
            initialScale: 1.02,
            initialBlur: 10,
            initialBrightness: 0.10,
            settleBrightness: 0.00,
            shadowColor: color(0.64, 0.74, 1.00),
            shadowOpacity: 0.14,
            shadowRadius: 13,
            shadowYOffset: 1,
            rotationDegrees: 4,
            duration: 0.37),
        .init(
            initialOpacity: 0.16,
            initialOffset: CGSize(width: 8, height: 12),
            initialScale: 0.95,
            initialBlur: 9,
            initialBrightness: 0.06,
            settleBrightness: 0.01,
            shadowColor: color(1.00, 0.70, 0.82),
            shadowOpacity: 0.12,
            shadowRadius: 12,
            shadowYOffset: 3,
            rotationDegrees: -3,
            duration: 0.35),
        .init(
            initialOpacity: 0.20,
            initialOffset: CGSize(width: -8, height: -12),
            initialScale: 1.05,
            initialBlur: 8,
            initialBrightness: 0.14,
            settleBrightness: 0.03,
            shadowColor: color(0.60, 0.94, 1.00),
            shadowOpacity: 0.10,
            shadowRadius: 11,
            shadowYOffset: 3,
            rotationDegrees: 3,
            duration: 0.32),
        .init(
            initialOpacity: 0.12,
            initialOffset: CGSize(width: 16, height: 0),
            initialScale: 0.91,
            initialBlur: 16,
            initialBrightness: 0.08,
            settleBrightness: 0.00,
            shadowColor: color(1.00, 0.76, 0.66),
            shadowOpacity: 0.18,
            shadowRadius: 18,
            shadowYOffset: 0,
            rotationDegrees: -8,
            duration: 0.45),
        .init(
            initialOpacity: 0.24,
            initialOffset: CGSize(width: -16, height: 0),
            initialScale: 1.07,
            initialBlur: 7,
            initialBrightness: 0.12,
            settleBrightness: 0.02,
            shadowColor: color(0.76, 0.72, 1.00),
            shadowOpacity: 0.14,
            shadowRadius: 12,
            shadowYOffset: 0,
            rotationDegrees: 8,
            duration: 0.34),
        .init(
            initialOpacity: 0.18,
            initialOffset: CGSize(width: 4, height: -14),
            initialScale: 1.03,
            initialBlur: 9,
            initialBrightness: 0.14,
            settleBrightness: 0.00,
            shadowColor: color(0.76, 1.00, 0.66),
            shadowOpacity: 0.12,
            shadowRadius: 10,
            shadowYOffset: 4,
            rotationDegrees: -1,
            duration: 0.31),
        .init(
            initialOpacity: 0.16,
            initialOffset: CGSize(width: -4, height: 14),
            initialScale: 0.96,
            initialBlur: 10,
            initialBrightness: 0.06,
            settleBrightness: 0.01,
            shadowColor: color(1.00, 0.84, 0.56),
            shadowOpacity: 0.16,
            shadowRadius: 14,
            shadowYOffset: 2,
            rotationDegrees: 1,
            duration: 0.38),
        .init(
            initialOpacity: 0.14,
            initialOffset: CGSize(width: 14, height: 8),
            initialScale: 0.92,
            initialBlur: 13,
            initialBrightness: 0.08,
            settleBrightness: 0.00,
            shadowColor: color(0.66, 0.86, 1.00),
            shadowOpacity: 0.18,
            shadowRadius: 17,
            shadowYOffset: 1,
            rotationDegrees: -6,
            duration: 0.43),
        .init(
            initialOpacity: 0.22,
            initialOffset: CGSize(width: -14, height: -8),
            initialScale: 1.06,
            initialBlur: 7,
            initialBrightness: 0.14,
            settleBrightness: 0.02,
            shadowColor: color(0.98, 0.68, 0.90),
            shadowOpacity: 0.12,
            shadowRadius: 10,
            shadowYOffset: 2,
            rotationDegrees: 6,
            duration: 0.33),
        .init(
            initialOpacity: 0.18,
            initialOffset: CGSize(width: 0, height: 16),
            initialScale: 0.98,
            initialBlur: 11,
            initialBrightness: 0.04,
            settleBrightness: 0.00,
            shadowColor: color(0.62, 0.98, 0.94),
            shadowOpacity: 0.14,
            shadowRadius: 13,
            shadowYOffset: 4,
            rotationDegrees: 0,
            duration: 0.36),
        .init(
            initialOpacity: 0.20,
            initialOffset: CGSize(width: 16, height: -4),
            initialScale: 0.93,
            initialBlur: 14,
            initialBrightness: 0.08,
            settleBrightness: 0.03,
            shadowColor: color(1.00, 0.92, 0.62),
            shadowOpacity: 0.16,
            shadowRadius: 15,
            shadowYOffset: 0,
            rotationDegrees: -7,
            duration: 0.42),
        .init(
            initialOpacity: 0.16,
            initialOffset: CGSize(width: -16, height: 4),
            initialScale: 1.04,
            initialBlur: 9,
            initialBrightness: 0.10,
            settleBrightness: 0.01,
            shadowColor: color(0.66, 0.78, 1.00),
            shadowOpacity: 0.14,
            shadowRadius: 12,
            shadowYOffset: 0,
            rotationDegrees: 7,
            duration: 0.37),
        .init(
            initialOpacity: 0.24,
            initialOffset: CGSize(width: 0, height: -16),
            initialScale: 1.06,
            initialBlur: 8,
            initialBrightness: 0.16,
            settleBrightness: 0.02,
            shadowColor: color(1.00, 0.72, 0.72),
            shadowOpacity: 0.12,
            shadowRadius: 11,
            shadowYOffset: 4,
            rotationDegrees: 0,
            duration: 0.32),
    ]

    package static func configuration(
        for preset: TokenDailyBoardConversationOnlyTextEffectPreset)
        -> TokenDailyBoardConversationOnlyTextEffectConfiguration
    {
        self.configs[preset.ordinal]
    }

    package static func intensityMultiplier(
        isWaitingGroup: Bool)
        -> Double
    {
        isWaitingGroup ? 0.72 : 1.0
    }
}

package enum TokenDailyBoardConversationOnlyPreviewSceneRules {
    static let sentence = TokenDailyBoardNarrativeSentence(
        id: "conversation-only-preview",
        text: "预览这套效果会直接应用到 live mode 1。",
        metadataText: "19:58:57 · 376,290 tokens")
}
