#!/usr/bin/env bash
set -euo pipefail
CONF=${1:-release}
ALLOW_LLDB=${CODEXBAR_ALLOW_LLDB:-0}
SIGNING_MODE=${CODEXBAR_SIGNING:-}
ROOT=$(cd "$(dirname "$0")/.." && pwd)
cd "$ROOT"

export HOME="${CODEXBAR_HOME:-$ROOT/.home}"
export CLANG_MODULE_CACHE_PATH="${CLANG_MODULE_CACHE_PATH:-$ROOT/.build/modulecache}"
export SWIFT_MODULECACHE_PATH="${SWIFT_MODULECACHE_PATH:-$CLANG_MODULE_CACHE_PATH}"
mkdir -p "$HOME" "$CLANG_MODULE_CACHE_PATH"
if [[ -z "${DEVELOPER_DIR:-}" ]] && [[ -d "/Applications/Xcode.app/Contents/Developer" ]]; then
  export DEVELOPER_DIR="/Applications/Xcode.app/Contents/Developer"
fi

# Load version info
source "$ROOT/version.env"
APP_DISPLAY_NAME="${CODEXBAR_APP_NAME:-CodexTokenBar}"
APP_EXECUTABLE_NAME="${CODEXBAR_EXECUTABLE_NAME:-CodexTokenBar}"
APP_BUNDLE_NAME="${CODEXBAR_APP_BUNDLE:-${APP_DISPLAY_NAME}.app}"
APP_STAGING_DIR="${CODEXBAR_APP_STAGING_DIR:-$ROOT/.build/apps}"
APP_INSTALL_PATH="${CODEXBAR_INSTALL_PATH:-/Applications/${APP_BUNDLE_NAME}}"
BUNDLE_ID_BASE="${CODEXBAR_BUNDLE_ID:-com.kevin.codextokenbar}"
DAILY_BOARD_APP_DISPLAY_NAME="${CODEXBAR_DAILY_BOARD_APP_NAME:-CodexDaily}"
DAILY_BOARD_EXECUTABLE_NAME="${CODEXBAR_DAILY_BOARD_EXECUTABLE_NAME:-CodexDaily}"
DAILY_BOARD_BUNDLE_NAME="${CODEXBAR_DAILY_BOARD_APP_BUNDLE:-${DAILY_BOARD_APP_DISPLAY_NAME}.app}"
DAILY_BOARD_BUNDLE_ID_BASE="${CODEXBAR_DAILY_BOARD_BUNDLE_ID:-com.kevin.codexdaily}"
DAILY_BOARD_STAGING_PATH="${APP_STAGING_DIR}/${DAILY_BOARD_BUNDLE_NAME}"
DAILY_BOARD_INSTALL_PATH="${CODEXBAR_DAILY_BOARD_INSTALL_PATH:-/Applications/${DAILY_BOARD_BUNDLE_NAME}}"
LEGACY_DAILY_BOARD_STAGING_PATH="${APP_STAGING_DIR}/CodexTokenBar Daily Board.app"
PACKAGE_MAIN_APP="${CODEXBAR_PACKAGE_MAIN_APP:-1}"
PACKAGE_DAILY_APP="${CODEXBAR_PACKAGE_DAILY_APP:-1}"

# Clean build only when explicitly requested (slower).
if [[ "${CODEXBAR_FORCE_CLEAN:-0}" == "1" ]]; then
  if [[ -d "$ROOT/.build" ]]; then
    if command -v trash >/dev/null 2>&1; then
      if ! trash "$ROOT/.build"; then
        echo "WARN: trash .build failed; continuing with swift package clean." >&2
      fi
    else
      rm -rf "$ROOT/.build" || echo "WARN: rm -rf .build failed; continuing with swift package clean." >&2
    fi
  fi
  swift package clean >/dev/null 2>&1 || true
fi

# Build for host architecture by default; allow overriding via ARCHES (e.g., "arm64 x86_64" for universal).
ARCH_LIST=( ${ARCHES:-} )
if [[ ${#ARCH_LIST[@]} -eq 0 ]]; then
  HOST_ARCH=$(uname -m)
  case "$HOST_ARCH" in
    arm64) ARCH_LIST=(arm64) ;;
    x86_64) ARCH_LIST=(x86_64) ;;
    *) ARCH_LIST=("$HOST_ARCH") ;;
  esac
fi

if [[ "${PACKAGE_MAIN_APP}" != "1" && "${PACKAGE_DAILY_APP}" != "1" ]]; then
  echo "ERROR: At least one of CODEXBAR_PACKAGE_MAIN_APP or CODEXBAR_PACKAGE_DAILY_APP must be enabled." >&2
  exit 1
fi

patch_keyboard_shortcuts() {
  local util_path="$ROOT/.build/checkouts/KeyboardShortcuts/Sources/KeyboardShortcuts/Utilities.swift"
  if [[ ! -f "$util_path" ]]; then
    return 0
  fi
  if grep -q "keyboardShortcutsSafeBundle" "$util_path"; then
    return 0
  fi

  chmod +w "$util_path" || true
  python3 - "$util_path" <<'PY'
import sys
from pathlib import Path

path = Path(sys.argv[1])
text = path.read_text()
if ".keyboardShortcutsSafeBundle" in text:
    sys.exit(0)

text = text.replace(
    'NSLocalizedString(self, bundle: .module, comment: self)',
    'NSLocalizedString(self, bundle: .keyboardShortcutsSafeBundle, comment: self)',
)

inject = """
private extension Bundle {
    /// Safe lookup that avoids the fatal trap in the autogenerated `Bundle.module`
    /// when the resource bundle is not placed at the bundle root.
    static let keyboardShortcutsSafeBundle: Bundle = {
        #if os(macOS)
        if let url = Bundle.main.url(forResource: "KeyboardShortcuts_KeyboardShortcuts", withExtension: "bundle"),
           let bundle = Bundle(url: url) {
            return bundle
        }

        let rootURL = Bundle.main.bundleURL.appendingPathComponent("KeyboardShortcuts_KeyboardShortcuts.bundle")
        if let bundle = Bundle(url: rootURL) {
            return bundle
        }
        #endif

        let devURL = URL(fileURLWithPath: #file)
            .deletingLastPathComponent()  // Utilities.swift
            .deletingLastPathComponent()  // KeyboardShortcuts
            .deletingLastPathComponent()  // Sources
            .appendingPathComponent("KeyboardShortcuts_KeyboardShortcuts.bundle")
        if let bundle = Bundle(url: devURL) {
            return bundle
        }

        return Bundle.main
    }()
}
"""

marker = "}\n\n\nextension Data {"
if marker not in text:
    raise SystemExit("Marker not found in Utilities.swift; patch failed.")

text = text.replace(marker, "}\n\n" + inject + "\n\nextension Data {")
path.write_text(text)
PY
}

KEYBOARD_SHORTCUTS_UTIL="$ROOT/.build/checkouts/KeyboardShortcuts/Sources/KeyboardShortcuts/Utilities.swift"
if [[ ! -f "$KEYBOARD_SHORTCUTS_UTIL" ]]; then
  bootstrap_product="CodexBar"
  if [[ "${PACKAGE_MAIN_APP}" != "1" && "${PACKAGE_DAILY_APP}" == "1" ]]; then
    bootstrap_product="CodexDaily"
  fi
  swift build -c "$CONF" --arch "${ARCH_LIST[0]}" --product "${bootstrap_product}"
fi
patch_keyboard_shortcuts

for ARCH in "${ARCH_LIST[@]}"; do
  if [[ "${PACKAGE_MAIN_APP}" == "1" ]]; then
    swift build -c "$CONF" --arch "$ARCH" --product CodexBar
  fi
  if [[ "${PACKAGE_DAILY_APP}" == "1" ]]; then
    swift build -c "$CONF" --arch "$ARCH" --product CodexDaily
  fi
done

APP_STAGING_PATH="${APP_STAGING_DIR}/${APP_BUNDLE_NAME}"
mkdir -p "$APP_STAGING_DIR"
rm -rf "$APP_STAGING_PATH" "$DAILY_BOARD_STAGING_PATH" "$LEGACY_DAILY_BOARD_STAGING_PATH"

TOKENBAR_ICON_TARGET="$ROOT/build/icon/CodexTokenBar/Icon.icns"
DAILY_BOARD_ICON_TARGET="$ROOT/build/icon/CodexDaily/Icon.icns"
"$ROOT/Scripts/build_icon.sh" >/dev/null

BUNDLE_ID="$BUNDLE_ID_BASE"
LOWER_CONF=$(printf "%s" "$CONF" | tr '[:upper:]' '[:lower:]')
if [[ "$LOWER_CONF" == "debug" ]]; then
  BUNDLE_ID="${BUNDLE_ID_BASE}.debug"
fi
ENTITLEMENTS_DIR="$ROOT/.build/entitlements"
APP_ENTITLEMENTS="${ENTITLEMENTS_DIR}/CodexBar.entitlements"
mkdir -p "$ENTITLEMENTS_DIR"
if [[ "$ALLOW_LLDB" == "1" && "$LOWER_CONF" != "debug" ]]; then
  echo "ERROR: CODEXBAR_ALLOW_LLDB requires debug configuration" >&2
  exit 1
fi
cat > "$APP_ENTITLEMENTS" <<PLIST
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE plist PUBLIC "-//Apple//DTD PLIST 1.0//EN" "http://www.apple.com/DTDs/PropertyList-1.0.dtd">
<plist version="1.0">
<dict>
    $(if [[ "$ALLOW_LLDB" == "1" ]]; then echo "    <key>com.apple.security.get-task-allow</key><true/>"; fi)
</dict>
</plist>
PLIST
BUILD_TIMESTAMP=$(date -u +"%Y-%m-%dT%H:%M:%SZ")
GIT_COMMIT=$(git rev-parse --short HEAD 2>/dev/null || echo "unknown")

build_product_path() {
  local name="$1"
  local arch="$2"
  case "$arch" in
    arm64|x86_64) echo ".build/${arch}-apple-macosx/$CONF/$name" ;;
    *) echo ".build/$CONF/$name" ;;
  esac
}

# Resolve path to built binary; some SwiftPM versions use .build/$CONF/ when building for host only.
resolve_binary_path() {
  local name="$1"
  local arch="$2"
  local candidate
  candidate=$(build_product_path "$name" "$arch")
  if [[ -f "$candidate" ]]; then
    echo "$candidate"
    return
  fi
  if [[ "$arch" == "arm64" || "$arch" == "x86_64" ]] && [[ -f ".build/$CONF/$name" ]]; then
    echo ".build/$CONF/$name"
  fi
}

resolve_codesign_identity() {
  local requested_identity="${CODEXBAR_SIGNING_IDENTITY:-${APP_IDENTITY:-}}"
  if [[ -n "$requested_identity" ]]; then
    printf '%s\n' "$requested_identity"
    return 0
  fi

  local detected_identity
  detected_identity=$(
    security find-identity -v -p codesigning 2>/dev/null |
      sed -n 's/.*"\(Developer ID Application:[^"]*\)".*/\1/p' |
      head -n 1
  )
  if [[ -n "$detected_identity" ]]; then
    printf '%s\n' "$detected_identity"
    return 0
  fi

  echo "ERROR: No Developer ID Application identity found. Set CODEXBAR_SIGNING_IDENTITY/APP_IDENTITY or use CODEXBAR_SIGNING=adhoc." >&2
  return 1
}

verify_binary_arches() {
  local binary="$1"; shift
  local expected=("$@")
  local actual
  actual=$(lipo -archs "$binary")
  local actual_count expected_count
  actual_count=$(wc -w <<<"$actual" | tr -d ' ')
  expected_count=${#expected[@]}
  if [[ "$actual_count" -ne "$expected_count" ]]; then
    echo "ERROR: $binary arch mismatch (expected: ${expected[*]}, actual: ${actual})" >&2
    exit 1
  fi
  for arch in "${expected[@]}"; do
    if [[ "$actual" != *"$arch"* ]]; then
      echo "ERROR: $binary missing arch $arch (have: ${actual})" >&2
      exit 1
    fi
  done
}

install_binary() {
  local name="$1"
  local dest="$2"
  local binaries=()
  for arch in "${ARCH_LIST[@]}"; do
    local src
    src=$(resolve_binary_path "$name" "$arch")
    if [[ -z "$src" || ! -f "$src" ]]; then
      echo "ERROR: Missing ${name} build for ${arch} at $(build_product_path "$name" "$arch")" >&2
      exit 1
    fi
    binaries+=("$src")
  done
  if [[ ${#ARCH_LIST[@]} -gt 1 ]]; then
    lipo -create "${binaries[@]}" -output "$dest"
  else
    cp "${binaries[0]}" "$dest"
  fi
  chmod +x "$dest"
  verify_binary_arches "$dest" "${ARCH_LIST[@]}"
}
if [[ "$SIGNING_MODE" == "adhoc" ]]; then
  CODESIGN_ID="-"
  CODESIGN_ARGS=(--force --sign "$CODESIGN_ID")
elif [[ "$ALLOW_LLDB" == "1" ]]; then
  CODESIGN_ID="-"
  CODESIGN_ARGS=(--force --sign "$CODESIGN_ID")
else
  CODESIGN_ID="$(resolve_codesign_identity)"
  CODESIGN_ARGS=(--force --timestamp --options runtime --sign "$CODESIGN_ID")
fi

# Bundle app resources (provider icons, etc.).
APP_RESOURCES_DIR="$ROOT/Sources/CodexBar/Resources"

create_app_bundle() {
  local app_path="$1"
  local display_name="$2"
  local executable_name="$3"
  local product_name="$4"
  local bundle_id="$5"
  local lsui_element="$6"
  local icon_source="$7"

  mkdir -p "$app_path/Contents/MacOS" "$app_path/Contents/Resources" "$app_path/Contents/Frameworks"
  mkdir -p "$app_path/Contents/Helpers"

  cat > "$app_path/Contents/Info.plist" <<PLIST
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE plist PUBLIC "-//Apple//DTD PLIST 1.0//EN" "http://www.apple.com/DTDs/PropertyList-1.0.dtd">
<plist version="1.0">
<dict>
    <key>CFBundleName</key><string>${display_name}</string>
    <key>CFBundleDisplayName</key><string>${display_name}</string>
    <key>CFBundleIdentifier</key><string>${bundle_id}</string>
    <key>CFBundleExecutable</key><string>${executable_name}</string>
    <key>CFBundlePackageType</key><string>APPL</string>
    <key>CFBundleShortVersionString</key><string>${MARKETING_VERSION}</string>
    <key>CFBundleVersion</key><string>${BUILD_NUMBER}</string>
    <key>LSMinimumSystemVersion</key><string>14.0</string>
    <key>LSUIElement</key><${lsui_element}/>
    <key>CFBundleIconFile</key><string>Icon</string>
    <key>NSHumanReadableCopyright</key><string>© 2025 Peter Steinberger. MIT License.</string>
    <key>CodexBuildTimestamp</key><string>${BUILD_TIMESTAMP}</string>
    <key>CodexGitCommit</key><string>${GIT_COMMIT}</string>
</dict>
</plist>
PLIST

  install_binary "$product_name" "$app_path/Contents/MacOS/${executable_name}"

  if [[ -f "$icon_source" ]]; then
    cp "$icon_source" "$app_path/Contents/Resources/Icon.icns"
  else
    echo "ERROR: Missing icon source at $icon_source" >&2
    exit 1
  fi

  if [[ "$product_name" == "CodexBar" && -d "$APP_RESOURCES_DIR" ]]; then
    cp -R "$APP_RESOURCES_DIR/." "$app_path/Contents/Resources/"
  fi
  if [[ "$product_name" == "CodexBar" && ! -f "$app_path/Contents/Resources/Icon-classic.icns" ]]; then
    echo "ERROR: Missing Icon-classic.icns in app bundle resources." >&2
    exit 1
  fi

  local built_binary preferred_build_dir
  built_binary="$(resolve_binary_path "$product_name" "${ARCH_LIST[0]}")"
  preferred_build_dir="$(dirname "${built_binary:-$(build_product_path "$product_name" "${ARCH_LIST[0]}")}")"
  shopt -s nullglob
  local swiftpm_bundles=("${preferred_build_dir}/"*.bundle)
  shopt -u nullglob
  if [[ ${#swiftpm_bundles[@]} -gt 0 ]]; then
    for bundle in "${swiftpm_bundles[@]}"; do
      local bundle_name
      bundle_name="$(basename "$bundle")"
      if [[ "$product_name" == "CodexBar" ]]; then
        case "$bundle_name" in
          *CodexDailyKit.bundle|*CodexDailyBoardShared.bundle|CodexDaily_*)
            continue
            ;;
        esac
      elif [[ "$product_name" == "CodexDaily" ]]; then
        case "$bundle_name" in
          *CodexDailyKit.bundle)
            ;;
          *)
            continue
            ;;
        esac
      fi
      cp -R "$bundle" "$app_path/Contents/Resources/"
    done
  fi

  chmod -R u+w "$app_path"
  xattr -cr "$app_path"
  find "$app_path" -name '._*' -delete

  codesign "${CODESIGN_ARGS[@]}" \
    --entitlements "$APP_ENTITLEMENTS" \
    "$app_path"

  echo "Created $app_path"
}

install_app_bundle() {
  local source_path="$1"
  local install_path="$2"
  local executable_name="$3"
  local temp_path="${install_path}.tmp.$$"

  mkdir -p "$(dirname "$install_path")"
  rm -rf "$temp_path"
  if ! /usr/bin/ditto "$source_path" "$temp_path"; then
    echo "ERROR: Failed to stage app install at $temp_path" >&2
    rm -rf "$temp_path"
    exit 1
  fi

  xattr -cr "$temp_path"
  find "$temp_path" -name '._*' -delete

  rm -rf "$install_path"
  if ! mv "$temp_path" "$install_path"; then
    echo "ERROR: Failed to install app to $install_path" >&2
    rm -rf "$temp_path"
    exit 1
  fi

  if [[ ! -x "$install_path/Contents/MacOS/${executable_name}" ]]; then
    echo "ERROR: Installed app is missing executable ${executable_name} at $install_path" >&2
    exit 1
  fi

  echo "Installed $install_path"
}

remove_legacy_daily_bundles() {
  local legacy_paths=(
    "/Applications/CodexTokenBar Daily Board.app"
    "/Applications/CodexDailyBoard.app"
  )

  for path in "${legacy_paths[@]}"; do
    if [[ "$path" != "$DAILY_BOARD_INSTALL_PATH" && -e "$path" ]]; then
      rm -rf "$path"
    fi
  done
}

DAILY_BOARD_BUNDLE_ID="$DAILY_BOARD_BUNDLE_ID_BASE"
if [[ "$LOWER_CONF" == "debug" ]]; then
  DAILY_BOARD_BUNDLE_ID="${DAILY_BOARD_BUNDLE_ID_BASE}.debug"
fi

if [[ "${PACKAGE_MAIN_APP}" == "1" ]]; then
  create_app_bundle "$APP_STAGING_PATH" "$APP_DISPLAY_NAME" "$APP_EXECUTABLE_NAME" "CodexBar" "$BUNDLE_ID" "true" "$TOKENBAR_ICON_TARGET"
  install_app_bundle "$APP_STAGING_PATH" "$APP_INSTALL_PATH" "$APP_EXECUTABLE_NAME"
fi

if [[ "${PACKAGE_DAILY_APP}" == "1" ]]; then
  create_app_bundle \
    "$DAILY_BOARD_STAGING_PATH" \
    "$DAILY_BOARD_APP_DISPLAY_NAME" \
    "$DAILY_BOARD_EXECUTABLE_NAME" \
    "CodexDaily" \
    "$DAILY_BOARD_BUNDLE_ID" \
    "false" \
    "$DAILY_BOARD_ICON_TARGET"
  remove_legacy_daily_bundles
  install_app_bundle "$DAILY_BOARD_STAGING_PATH" "$DAILY_BOARD_INSTALL_PATH" "$DAILY_BOARD_EXECUTABLE_NAME"
fi
